version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - echo Setting up Maven dependencies...

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Post-build phase started on `date`
      - echo Build completed successfully

artifacts:
  files:
    - target/backend-app.jar
    - appspec.yml
    - scripts/**/*
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'